Areas/Admin/Models/ViewModels/MainViewModel.cs
using DocWorkflow.Areas.Admin.Models.DataModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace Admin.ViewModels
{
    /// <summary>
    /// Модель главного представления
    /// </summary>
    public class MainViewModel
    {
        /// <summary>
        /// Текущий авторизованный пользователь
        /// </summary>
        public User CurrentUser { get; set; }

        /// <summary>
        /// Строка с ФИО текущего пользователя
        /// </summary>
        public String UserAuthorizationStatus
        {
            get
            {
                if(Authentication.User!=null)
                {
                    return Authentication.User.UserName + " (" + Authentication.User.UserGroup.Name + ")";
                }
                else
                {
                    return "";
                }
            }
        }


        /// <summary>
        /// Инициализация модели
        /// </summary>
        public void InitModel()
        {
            DataContext ctx = new DataContext();
            CurrentUser = ctx.User.Find(Authentication.User.UserId);
        }
    }
}

Areas/Admin/Controllers/DocTypeController.cs
using Ext.Net;
using Ext.Net.MVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using DocWorkflow.Areas.Admin.Models.DataModels;

namespace Admin.Controllers
{
    /// <summary>
    /// Контроллер формы редактирования видов документов
    /// </summary>
    public class DocTypeController : Controller
    {
        /// <summary>
        /// Отображение формы создания новой записи
        /// </summary>
        /// <param name="onCloseClientScript">Клиентский javascript, который следует выполнить при закрытии окна</param>
        /// <returns></returns>
        public ActionResult CreateNew(String onCloseClientScript = null)
        {
            DocType model = new DocType();
            model.InitNewObject();

            Ext.Net.MVC.PartialViewResult result = new Ext.Net.MVC.PartialViewResult()
            {
                ViewName = "EditForm",
                WrapByScriptTag = false,
                Model = model,
                RenderMode = RenderMode.Auto
            };

            if (String.IsNullOrWhiteSpace(onCloseClientScript) || onCloseClientScript == "null")
                onCloseClientScript = "{}";

            result.ViewBag.OnCloseClientScript = onCloseClientScript;
            result.ViewBag.IsNew = true;

            return result;
        }


        /// <summary>
        /// Отображение формы редактирования существующей записи
        /// </summary>
        /// <param name="id"></param>
        /// <param name="onCloseClientScript">Клиентский javascript, который следует выполнить при закрытии окна</param>
        /// <returns></returns>
        public ActionResult OpenExisting(int id, String onCloseClientScript = null)
        {
            DataContext ctx = new DataContext();
            DocType model = ctx.DocType.AsNoTracking().FirstOrDefault(u => u.DocTypeId == id);
            if (model == null)
                throw new Exception("Объект не существует");

            Ext.Net.MVC.PartialViewResult result = new Ext.Net.MVC.PartialViewResult()
            {
                ViewName = "EditForm",
                WrapByScriptTag = false,
                Model = model,
                RenderMode = RenderMode.Auto
            };

            if (String.IsNullOrWhiteSpace(onCloseClientScript) || onCloseClientScript == "null")
                onCloseClientScript = "{}";

            result.ViewBag.OnCloseClientScript = onCloseClientScript;
            result.ViewBag.IsNew = false;

            return result;
        }


        /// <summary>
        /// Получение всех элементов
        /// </summary>
        /// <returns></returns>
        public ActionResult GetAllItems()
        {
            using (DataContext ctx = new DataContext())
            {
                var items = from item in ctx.DocType.Include(t => t.Documents).AsNoTracking()
                            orderby item.DocTypeName
                            select new
                            {
                                item.DocTypeId,
                                item.DocTypeName,
                                DocumentsCount = item.Documents.Count
                            };

                return this.Store(items.ToList());
            }
        }


        /// <summary>
        /// Удаление элемента
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            using (DataContext ctx = new DataContext())
            {
                DocType item = ctx.DocType.Find(id);

                if (item != null)
                {
                    String msg = item.CheckCanDelete();
                    if (String.IsNullOrEmpty(msg))
                    {
                        ctx.DocType.Remove(item);

                        try
                        {
                            ctx.SaveChanges();
                        }
                        catch
                        {
                            X.Msg.Alert("Внимание!", "Элемент справочника не может быть удален, т.к. от этого элемента зависит один или несколько объектов.").Show();
                        }
                    }
                    else
                    {
                        X.Msg.Alert("Внимание!", msg).Show();
                    }
                }

                return this.Direct();
            }
        }


        /// <summary>
        /// Сохранение данных и закрытие окна
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult Save(DocType model)
        {
            try
            {
                String msg = model.Validate();
                if (!String.IsNullOrEmpty(msg))
                {
                    X.Msg.Alert("Ошибка", msg).Show();
                    return this.Direct();
                }

                DataContext ctx = new DataContext();
                DocType item = ctx.DocType.Find(model.DocTypeId);
                if (item == null)
                {
                    ctx.DocType.Add(model);
                    item = model;
                }
                else
                {
                    item.DocTypeName = model.DocTypeName;
                    item.DocTypeId = model.DocTypeId;
                }

                ctx.SaveChanges();

                X.GetCmp<Window>("DocType_window").Close();
                return this.Direct();
            }
            catch (Exception ex)
            {
                return this.Direct(false, ex.Message);
            }
        }        
    }
}

Areas/Admin/Controllers/UserController.cs
using Ext.Net;
using Ext.Net.MVC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using DocWorkflow.Areas.Admin.Models.DataModels;

namespace Admin.Controllers
{
    /// <summary>
    /// Контроллер формы редактирования пользователей
    /// </summary>
    public class UserController : Controller
    {
        /// <summary>
        /// Отображение формы создания новой записи
        /// </summary>
        /// <param name="onCloseClientScript">Клиентский javascript, который следует выполнить при закрытии окна</param>
        /// <returns></returns>
        public ActionResult CreateNew(String onCloseClientScript = null)
        {
            User model = new User();
            model.InitNewObject();

            Ext.Net.MVC.PartialViewResult result = new Ext.Net.MVC.PartialViewResult()
            {
                ViewName = "EditForm",
                WrapByScriptTag = false,
                Model = model,
                RenderMode = RenderMode.Auto
            };

            if (String.IsNullOrWhiteSpace(onCloseClientScript) || onCloseClientScript == "null")
                onCloseClientScript = "{}";

            result.ViewBag.OnCloseClientScript = onCloseClientScript;
            result.ViewBag.IsNew = true;
            result.ViewBag.UserGroups = GetUserGroups();
            result.ViewBag.Departments = GetDepartments();

            return result;
        }


        /// <summary>
        /// Отображение формы редактирования существующей записи
        /// </summary>
        /// <param name="id"></param>
        /// <param name="onCloseClientScript">Клиентский javascript, который следует выполнить при закрытии окна</param>
        /// <returns></returns>
        public ActionResult OpenExisting(int id, String onCloseClientScript = null)
        {
            DataContext ctx = new DataContext();
            User model = ctx.User.AsNoTracking().FirstOrDefault(u => u.UserId == id);
            if (model == null)
                throw new Exception("Объект не существует");

            Ext.Net.MVC.PartialViewResult result = new Ext.Net.MVC.PartialViewResult()
            {
                ViewName = "EditForm",
                WrapByScriptTag = false,
                Model = model,
                RenderMode = RenderMode.Auto
            };

            if (String.IsNullOrWhiteSpace(onCloseClientScript) || onCloseClientScript == "null")
                onCloseClientScript = "{}";

            result.ViewBag.OnCloseClientScript = onCloseClientScript;
            result.ViewBag.IsNew = false;
            result.ViewBag.UserGroups = GetUserGroups();
            result.ViewBag.Departments = GetDepartments();

            return result;
        }


        /// <summary>
        /// Получение списка групп пользователя
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        private List<UserGroup> GetUserGroups()
        {
            using (DataContext ctx = new DataContext())
            {
                var groups = ctx.UserGroup.OrderBy(t => t.Name).ToList();
                return groups;
            }
        }


        /// <summary>
        /// Получение списка подразделений
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        private List<Department> GetDepartments()
        {
            IEnumerable<Department> deptItems;
            using (DataContext ctx = new DataContext())
            {
                deptItems = ctx.Department
                    .OrderBy(t => t.DepartmentName)
                    .ToList();
            }

            return deptItems.Select(t =>
                new Department()
                {
                    DepartmentId = t.DepartmentId,
                    DepartmentName = t.DepartmentName,
                    DepartmentHeadId = t.DepartmentHeadId
                })
                .ToList();
        }


        /// <summary>
        /// Получение всех элементов
        /// </summary>
        /// <returns></returns>
        public ActionResult GetAllItems()
        {
            using (DataContext ctx = new DataContext())
            {
                var items = from item in ctx.User.AsNoTracking()
                            orderby item.UserName
                            select new
                            {
                                item.UserId,
                                item.UserName,
                                item.UserLogin,
                                UserGroupName = item.UserGroup.Name,
                                DepartmentName = item.Department.DepartmentName,
                                Position = item.Position,
                                item.IsActive
                            };

                return this.Store(items.ToList());
            }
        }


        /// <summary>
        /// Получение объекта по ID и возврат на клиент в виде DirectResult
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult GetById(int id)
        {
            using (DataContext ctx = new DataContext())
            {
                User item = ctx.User
                    .Include(u => u.UserGroup)
                    .Include(u => u.Department)
                    .AsNoTracking()
                    .First(u => u.UserId == id);

                DirectResult result = this.Direct();
                result.Result = new User()
                {
                    UserId = item.UserId,
                    UserName = item.UserName,
                    UserLogin = item.UserLogin,
                    UserGroup_UserGroupId = item.UserGroup_UserGroupId,
                    DepartmentId = item.Department.DepartmentId,
                    Position = item.Position,
                    IsActive = item.IsActive
                };
                return result;
            }
        }


        /// <summary>
        /// Удаление элемента
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(int id)
        {
            using (DataContext ctx = new DataContext())
            {
                User item = ctx.User.Find(id);

                if (item != null)
                {
                    String msg = item.CheckCanDelete();
                    if (String.IsNullOrEmpty(msg))
                    {
                        ctx.User.Remove(item);

                        try
                        {
                            ctx.SaveChanges();
                        }
                        catch
                        {
                            X.Msg.Alert("Внимание!", "Учетная запись пользователя не может быть удалена из системы, т.к. от данной учетной записи зависит один или несколько объектов. Вместо удаления рекомендуется отключить вход для выбранной учетной записи.").Show();
                        }
                    }
                    else
                    {
                        X.Msg.Alert("Внимание!", msg).Show();
                    }
                }

                return this.Direct();
            }
        }


        /// <summary>
        /// Сохранение данных и закрытие окна
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public ActionResult Save(User model)
        {
            try
            {
                String msg = model.Validate();
                if (!String.IsNullOrEmpty(msg))
                {
                    X.Msg.Alert("Ошибка", msg).Show();
                    return this.Direct();
                }

                DataContext ctx = new DataContext();
                User item = ctx.User.Find(model.UserId);
                if (item == null)
                {
                    ctx.User.Add(model);
                    item = model;
                }
                else
                {
                    item.UserLogin = model.UserLogin;
                    item.UserName = model.UserName;
                    item.UserGroup_UserGroupId = model.UserGroup_UserGroupId;
                    item.DepartmentId = model.DepartmentId;
                    item.Position = model.Position;
                    item.IsActive = model.IsActive;
                }

                ctx.SaveChanges();

                X.GetCmp<Window>("User_window").Close();
                return this.Direct();
            }
            catch (Exception ex)
            {
                return this.Direct(false, ex.Message);
            }
        }        
    }
}

Areas/Admin/Views/Main/TabDocType.cshtml
@using System;
@using System.Linq;
@using Ext.Net;
@using Ext.Net.MVC;
@using System.Web;
@using System.Web.Mvc;

@model Admin.ViewModels.MainViewModel

@{
    var X = Ext.Net.Html.X();
    bool UserCanEdit = Authentication.UserIsSysadmin;
}

<script type="text/javascript">

    
    function TabDocType_GetSelectedId() {
        var sel = App.TabDocType_grid.getSelectionModel().getSelection();
        if (sel.length > 0)
            return sel[0].get("DocTypeId");
        else
            return -1;
    }


    function TabDocType_Edit() {
        var id = TabDocType_GetSelectedId();
        if (id > 0) {
            Ext.net.Mask.show();
            Ext.net.DirectMethod.request(
                {
                    url: "/Admin/DocType/OpenExisting",
                    params: {
                        id: id,
                        onCloseClientScript: "TabDocType_Refresh();"
                    },
                    success: function (result) { Ext.net.Mask.hide(); },
                    failure: function (errorMessage) { Ext.net.Mask.hide(); Ext.Msg.alert('Ошибка', errorMessage); }
                });
        }
        else {
            Ext.MessageBox.alert('Внимание!', 'Необходимо выбрать запись для редактирования.');
        }
    }
    
    function TabDocType_Create() {
        Ext.net.Mask.show();
        Ext.net.DirectMethod.request(
            {
                url: "/Admin/DocType/CreateNew",
                params:{
                    onCloseClientScript: "TabDocType_Refresh();"
                },
                success: function (result) { Ext.net.Mask.hide(); },
                failure: function (errorMessage) { Ext.net.Mask.hide(); Ext.Msg.alert('Ошибка', errorMessage); }
            });
    }


    function TabDocType_Delete() {
        var id = TabDocType_GetSelectedId();
        if (id > 0) {
            Ext.MessageBox.show({
                title: 'Подтверждение удаления',
                msg: 'Удалить выбранную запись из справочника?',
                buttons: Ext.MessageBox.YESNO,
                fn: function (btn) {
                    if (btn == 'yes') {
                        Ext.net.DirectMethod.request({
                            url: "/Admin/DocType/Delete?id=" + id,
                            success: function (result) { TabDocType_Refresh(); },
                            failure: function (errorMessage) { TabDocType_Refresh(); Ext.Msg.alert('Ошибка', errorMessage); }
                        });
                    }
                },
                icon: Ext.MessageBox.WARNING
            });
        }
        else {
            Ext.MessageBox.alert('Внимание!', 'Необходимо выбрать запись для удаления.');
        }
    }

    
    function TabDocType_Refresh() {
        App.TabDocType_grid.setLoading(true);
        App.TabDocType_store.reload({
            callback: function () {
                App.TabDocType_grid.setLoading(false);
            }
        });
    }
</script>

@(    
    X.Container()
        .Layout(LayoutType.Border)
        .Items(

            X.GridPanel()
                .ID("TabDocType_grid")
                .Region(Region.Center)
                .AutoScroll(true)
                .RowLines(true)
                .ColumnLines(true)
                .Store(X.Store()
                    .ID("TabDocType_store")
                    .Model(X.Model()
                        .IDProperty("DocTypeId")
                        .Fields(
                            new ModelField("DocTypeId", ModelFieldType.Int),
                            new ModelField("DocTypeName")
                        )
                    )
                    .ServerProxy(X.AjaxProxy()
                        .Url(Url.Action("GetAllItems", "DocType"))
                        .ActionMethods(am => am.Read = HttpMethod.POST)
                        .Reader(X.JsonReader().RootProperty("data"))
                    )
                )
                .ColumnModel(
                    X.Column()
                        .Text("<b>Вид документа</b>")
                        .DataIndex("DocTypeName")
                        .Flex(1)
                        .MinWidth(140)
                        .CellWrap(true)
                        .Filterable(true)
                        .Filter(X.StringFilter()),
                    X.Column()
                        .Text("<b>Кол-во документов</b>")
                        .DataIndex("DocumentsCount")
                        .Width(160)
                        .CellWrap(true)
                        .Filterable(true)
                        .Align(Alignment.Center)
                        .Filter(X.NumberFilter())
                )
                .TopBar(
                    X.Toolbar()
                        .Items(
                            X.Button().Icon(Icon.Add)
                                .Text("Добавить...")
                                .Hidden(!UserCanEdit)
                                .Handler("TabDocType_Create()"),
                            X.Button().Icon(Icon.Delete)
                                .Text("Удалить")
                                .Hidden(!UserCanEdit)
                                .Handler("TabDocType_Delete()"),
                            X.Button().Icon(Icon.ArrowRefresh)
                                .Text("Обновить")
                                .Handler("TabDocType_Refresh()")
                        )
                )
                .SelectionModel(
                    X.RowSelectionModel()
                )
                .Listeners(ls =>
                {
                    ls.BoxReady.Handler = "TabDocType_Refresh()";

                    if (UserCanEdit)
                        ls.CellDblClick.Handler = "TabDocType_Edit();";
                })
                .Plugins(
                    X.GridFilters()
                        .MenuFilterText("Фильтр")
                )
        )
)

Areas/Admin/Views/Main/TabUser.cshtml
@using System;
@using System.Linq;
@using Ext.Net;
@using Ext.Net.MVC;
@using System.Web;
@using System.Web.Mvc;

@model Admin.ViewModels.MainViewModel

@{
    var X = Ext.Net.Html.X();
    bool UserCanEdit = Authentication.UserIsSysadmin;
}

<script type="text/javascript">

    
    function TabUser_GetSelectedId() {
        var sel = App.TabUser_grid.getSelectionModel().getSelection();
        if (sel.length > 0)
            return sel[0].get("UserId");
        else
            return -1;
    }


    function TabUser_Edit() {
        var id = TabUser_GetSelectedId();
        if (id > 0) {
            Ext.net.Mask.show();
            Ext.net.DirectMethod.request(
                {
                    url: "/Admin/User/OpenExisting",
                    params: {
                        id: id,
                        onCloseClientScript: "TabUser_Refresh();"
                    },
                    success: function (result) { Ext.net.Mask.hide(); },
                    failure: function (errorMessage) { Ext.net.Mask.hide(); Ext.Msg.alert('Ошибка', errorMessage); }
                });
        }
        else {
            Ext.MessageBox.alert('Внимание!', 'Необходимо выбрать элемент для редактирования.');
        }
    }
    
    function TabUser_Create() {
        Ext.net.Mask.show();
        Ext.net.DirectMethod.request(
            {
                url: "/Admin/User/CreateNew",
                params:{
                    onCloseClientScript: "TabUser_Refresh();"
                },
                success: function (result) { Ext.net.Mask.hide(); },
                failure: function (errorMessage) { Ext.net.Mask.hide(); Ext.Msg.alert('Ошибка', errorMessage); }
            });
    }


    function TabUser_Delete() {
        var id = TabUser_GetSelectedId();
        if (id > 0) {
            Ext.MessageBox.show({
                title: 'Подтверждение удаления',
                msg: 'Удалить выбранного пользователя?',
                buttons: Ext.MessageBox.YESNO,
                fn: function (btn) {
                    if (btn == 'yes') {
                        Ext.net.DirectMethod.request({
                            url: "/Admin/User/Delete?id=" + id,
                            success: function (result) { TabUser_Refresh(); },
                            failure: function (errorMessage) { TabUser_Refresh(); Ext.Msg.alert('Ошибка', errorMessage); }
                        });
                    }
                },
                icon: Ext.MessageBox.WARNING
            });
        }
        else {
            Ext.MessageBox.alert('Внимание!', 'Необходимо выбрать элемент для удаления.');
        }
    }

    
    function TabUser_Refresh() {
        App.TabUser_grid.setLoading(true);
        App.TabUser_store.reload({
            callback: function () {
                App.TabUser_grid.setLoading(false);
            }
        });
    }
</script>

@(    
    X.Container()
        .Layout(LayoutType.Border)
        .Items(

            X.GridPanel()
                .ID("TabUser_grid")
                .Region(Region.Center)
                .AutoScroll(true)
                .RowLines(true)
                .ColumnLines(true)
                .Store(X.Store()
                    .ID("TabUser_store")
                    .Model(X.Model()
                        .IDProperty("UserId")
                        .Fields(
                            new ModelField("UserId", ModelFieldType.Int),
                            new ModelField("UserLogin"),
                            new ModelField("UserName"),
                            new ModelField("UserGroupName"),
                            new ModelField("DepartmentName"),
                            new ModelField("Position"),
                            new ModelField("IsActive", ModelFieldType.Boolean)
                        )
                    )
                    .ServerProxy(X.AjaxProxy()
                        .Url(Url.Action("GetAllItems", "User"))
                        .ActionMethods(am => am.Read = HttpMethod.POST)
                        .Reader(X.JsonReader().RootProperty("data"))
                    )
                )
                .ColumnModel(
                    X.Column()
                        .Text("<b>Логин</b>")
                        .DataIndex("UserLogin")
                        .Flex(1)
                        .CellWrap(true)
                        .Filterable(true)
                        .Filter(X.StringFilter()),
                    X.Column()
                        .Text("<b>ФИО</b>")
                        .DataIndex("UserName")
                        .Flex(1)
                        .CellWrap(true)
                        .Filterable(true)
                        .Filter(X.StringFilter()),
                    X.Column()
                        .Text("<b>Роль</b>")
                        .DataIndex("UserGroupName")
                        .Flex(1)
                        .CellWrap(true)
                        .Filterable(true)
                        .Filter(X.ListFilter()),
                    X.Column()
                        .Text("<b>Подразделение</b>")
                        .DataIndex("DepartmentName")
                        .Flex(1)
                        .CellWrap(true)
                        .Filterable(true)
                        .Filter(X.ListFilter()),
                    X.Column()
                        .Text("<b>Должность</b>")
                        .DataIndex("Position")
                        .Flex(1)
                        .CellWrap(true)
                        .Filterable(true)
                        .Filter(X.ListFilter()),
                    X.CheckColumn()
                        .Text("<b>Разрешить вход</b>")
                        .DataIndex("IsActive")
                        .Width(130)
                        .Editable(false)
                        .Filterable(true)
                        .Filter(X.BooleanFilter().YesText("Да").NoText("Нет"))
                )
                .TopBar(
                    X.Toolbar()
                        .Items(
                            X.Button().Icon(Icon.Add)
                                .Text("Новый пользователь...")
                                .Hidden(!UserCanEdit)
                                .Handler("TabUser_Create()"),
                            X.Button().Icon(Icon.Delete)
                                .Text("Удалить")
                                .Hidden(!UserCanEdit)
                                .Handler("TabUser_Delete()"),
                            X.Button().Icon(Icon.ArrowRefresh)
                                .Text("Обновить")
                                .Handler("TabUser_Refresh()")
                        )
                )
                .SelectionModel(
                    X.RowSelectionModel()
                )
                .Listeners(ls =>
                {
                    ls.BoxReady.Handler = "TabUser_Refresh()";

                    if (UserCanEdit)
                        ls.CellDblClick.Handler = "TabUser_Edit();";
                })
                .Plugins(
                    X.GridFilters()
                        .MenuFilterText("Фильтр")
                )
        )
)